In [3]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
a[::-1]

array([3, 2, 1])

In [26]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.ones([1,6])

array([[1., 1., 1., 1., 1., 1.]])

In [43]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
b[::-1]

array([[4, 5, 6],
       [1, 2, 3]])